application: google.com:dragonwell
version: 1
instance_class: F4_1G
runtime: go
api_version: go1

handlers:
- url: /(.*\.(gif|png|jpg))$
  static_files: google3/ops/netopscorp/dragonwell/go/static/\1
  upload: google3/ops/netopscorp/dragonwell/go/static/.*\.(gif|png|jpg)$

- url: /.*
  script: _go_app
