application: tte.com:dw
version: 1
instance_class: F4_1G
runtime: go
api_version: go1

handlers:
- url: /(.*\.(gif|png|jpg))$
  static_files: .../go/static/\1
  upload: .../go/static/.*\.(gif|png|jpg)$

- url: /.*
  script: _go_app
